### ISSUE TITLE
Link?

### ISSUE THREAD

**Issue by abdullah2993** [SMUsamaShah/LookupChatGPT#1]
Shah g, extension ka link he daal dain

**Comment by SMUsamaShah** [comment]
Abhi store pe nai.

1. Download repo in a folder
2. chrome://extensions/
3. Turn on Developer mode
4. Click `Load unpacked` button
5. Path to that folder

**Comment by abdullah2993** [comment]
Shah g itni mehnt nai hoti

**Comment by SMUsamaShah** [comment]
Submitted, time lagey ga

**Comment by SMUsamaShah** [comment]
https://chrome.google.com/webstore/detail/lookup-selected-text-via/eehddkmcdpoojccopfpbcplffmcaffec
